const labels: Record<string, string> = {
 APPLICATION_RESPONSE: '지원서 답변', VALUES_BEHAVIOR_INTERVIEW: '2차 행동 면접', DOCUMENT_REVIEW: '서류 검토', CODING_TEST: '코딩테스트', TECHNICAL_ASSESSMENT: '기술평가', AI_CASE: 'AI 문제해결 과제', PRACTITIONER_QA: '실무진 질의', SECOND_INTERVIEW: '2차면접', FOCUSED_FOLLOW_UP: '추가 확인',
 SELF_REPORTED: '자기기술', DIRECT_TASK: '직접 과제', DIRECT_INTERACTION: '직접 질의', BEHAVIORAL_INTERACTION: '과거 행동 확인',
 NOT_OBSERVED: '직접 확인되지 않음', LIMITED: '제한적 근거', MODERATE: '충분한 근거', STRONG: '강한 근거', AGREED: '합의', DISAGREEMENT_REMAINS: '의견 차이 남음', INSUFFICIENT_EVIDENCE: '판단 근거 부족',
 ADVANCED: '다음 단계 진행', FAILED: '직접 근거에 따른 비진행', IN_PROGRESS: '대기 / 확인 중', EVIDENCE_PENDING: '판단 근거 대기', WITHDRAWN: '철회', HOLD: '추가 확인 보류', MISSING_EVIDENCE: '필요 근거 미확보', EVALUATOR_DISAGREEMENT: '평가자 해석 차이', UNRESOLVED_EVIDENCE: '근거의 불확실성 미해결',
 PROCEED_TO_OFFER: '채용 제안 진행', DO_NOT_PROCEED: '이번 채용 진행 종료', ARTIFACT_UNAVAILABLE: '필요 산출물 미확보', OWNERSHIP_TRACE_SUPPLIED: '본인 수행·검증 기록 확보',
 ML_ENGINEER: 'ML 엔지니어', HIRING_MANAGER: '현업 채용책임자', TECHNICAL_REVIEWER: '기술 평가자', RECRUITER: '채용담당자',
 DOCUMENT_SCREEN: '서류', PRE_ASSESSMENT: '사전검증', FIRST_INTERVIEW: '1차면접', FINAL_REVIEW: '최종 검토', INITIAL: '최초 검토', RE_REVIEW: '재검토',
 MUST: '입사 전 필수', LEARNABLE: '입사 후 학습 가능', PLUS: '추가 강점', SAME_EVIDENCE_EVALUATOR_DISAGREEMENT: '동일 근거에 대한 평가자 해석 차이', DIRECT_EVIDENCE_CONFLICT: '직접 근거 사이의 충돌',
};
export function label(value: string) { return labels[value] ?? value; }
export function copy(value: string) { return value.replaceAll('planned_ready_at', '업무 준비 목표일').replaceAll('learnable_gap_summary', '개인별 학습 과제').replaceAll('post-join Work Evidence', '입사 후 업무 근거').replaceAll('READY_CONFIRMED', '업무 준비 확인').replaceAll('effective_at', '인력 반영 시각').replaceAll('Task', '업무 과제').replaceAll('persisted', '저장된').replaceAll('uncertainty', '불확실성').replaceAll('Resolution Plan', '추가 확인 계획').replaceAll('Focused Follow-up', '추가 확인').replaceAll('RE_REVIEW', '재검토').replaceAll('INITIAL', '최초').replaceAll('Reason', '이유').replaceAll('new ', '새 ').replaceAll('Actual', '실제').replaceAll('Goal Briefing', '목표 브리핑').replaceAll('Forecast', '목표일 공급 전망').replaceAll('Skill Decision', '역량별 판단').replaceAll('Human Confirmation', '사람의 확인').replaceAll('Human Decision', '사람의 판단').replaceAll('Initial Plan', '최초 계획').replaceAll('Revised Capacity', '변경 후 시간').replaceAll('Capacity', '운영시간').replaceAll('Demand', '수요').replaceAll('Gap', '차이').replaceAll('Targeted Follow-up', '추가 확인').replaceAll('Evidence', '근거').replaceAll('Skill', '역량').replaceAll('Observation', '관찰').replaceAll('Calibration', '평가 조정').replaceAll('Re-review Proceed', '재검토 후 제안 진행').replaceAll('Offer EXPIRED', '제안 기한 만료').replaceAll('Selection', '선발').replaceAll('lifecycle', '진행 이력').replaceAll('NOT_OBSERVED', '미관찰').replaceAll('MODERATE', '충분한 근거').replaceAll('HOLD', '보류').replaceAll('Offer', '채용 제안').replaceAll('Plan', '계획').replaceAll('Session', '면접').replaceAll('decisionable Coverage', '판단 가능한 근거 범위').replaceAll('Coverage', '근거 범위').replaceAll('NOT_OBSERVED', '미관찰').replaceAll('LIMITED', '제한적 근거').replaceAll('Learnable', '입사 후 학습').replaceAll('Must', '필수 역량').replaceAll('MUST', '필수 역량').replaceAll('Rubric', '판단 기준').replaceAll('Target', '대상').replaceAll('Message', '메시지').replaceAll('Content', '콘텐츠').replaceAll('Channel', '채널').replaceAll('Matrix', '평가 연결표'); }
export const sceneTitles: Record<string, string> = { 'M1-03': '인재 요건 논의', 'M1-09': '채용 규모 계획', 'M1-12': '면접 운영시간 재검토', 'M1-18': '보류 후 추가 확인', 'M1-19': '평가 조정과 최종 재검토', 'M1-20': '채용 제안', 'M1-21': '입사', 'M1-22': '업무 적응', 'M1-23': '업무 준비 확인', 'M1-25': 'Mission 1 마무리' };
