import data from './view.json';
import { label } from './labels';
const p = data.workforcePlan, c = data.capacity, o = data.outcomes;
export function Facts({ items }: { items: [string, string | number][] }) { return <dl className="m1-facts">{items.map(([name, value]) => <div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl>; }
export function Funnel({ actual = false }: { actual?: boolean }) { return <><table className="m1-table" data-funnel={actual ? 'actual' : 'plan'}><caption>고유 지원자 수 · 단위: 명 · {actual ? `v1 관측 종료 ${data.observationEnd.slice(0, 10)}` : '사전에 정한 계획'}</caption><thead><tr><th>구간</th><th>계획</th>{actual && <th>실제</th>}</tr></thead><tbody>{data.funnel.map(f => <tr key={f.stage}><th>{({ FIRST_INTERVIEW: '1차면접 대상', JOIN: '입사', OFFER: '채용 제안' } as Record<string, string>)[f.stage] ?? f.label}</th><td>{f.target}</td>{actual && <td data-actual={f.stage}>{f.actual}</td>}</tr>)}</tbody></table><p className="m1-note">계획은 정원이 아닙니다. 실제 결과를 목표 숫자에 맞추지 않았습니다.</p></>; }
export function Capacity({ phase = 2 }: { phase?: number }) { return <div data-capacity><Facts items={[["최초 계획", `${c.initial}h`], ["후보당 면접 노력", `${c.unit} person-hours`], ["계획 면접 인원", `${c.planned}명`]]} />
 {phase >= 1 && <><h4>수요와 부족 시간 확인</h4><Facts items={[["실제 면접 수요", `${data.interview.entered}명`], ["필요 시간", `${c.demand}h`], ["부족 시간", `${c.gap}h`]]} /><p>{data.interview.entered}명 × {c.unit}h = {c.demand}h. 부족 시간은 {c.demand} − {c.initial} = {c.gap}h입니다.</p><p>운영시간 부족으로 후보자를 탈락시키지 않습니다.</p></>}
 {phase >= 2 && <><h4>사람의 운영 결정 → 일정 반영</h4><p>기간 연장과 평가방식 변경을 검토한 뒤, 추가 평가자 시간을 확보했습니다.</p><Facts items={[["추가 확보", `${c.additional}h`], ["변경 후 총량", `${c.revised}h`], ["면접 예약", `${c.reserved}h`]]} /><p>{c.pool}명의 합성 평가자에게 각각 {c.decision.additional_hours_each}h를 추가 배분했습니다. 최초 {c.initial}h 기록은 보존합니다.</p><p className="m1-note">평가자 규모와 시간 배분은 합성 운영 가정입니다. 기아 실제 운영을 뜻하지 않습니다.</p><details><summary>계산과 기록 출처</summary><p>부족 시간을 평가자당 1h 단위로 배분: ⌈{c.gap} ÷ {c.pool}⌉ × {c.pool} = {c.additional}h.</p><code>v1/interview_capacity_events.csv · {c.sourceIds.join(' → ')}</code></details></>}
 </div>; }
export default function SceneContent({ id, phase }: { id: string; phase: number }) {
 switch (id) {
 case 'M1-01': return <><p>가상 AI/ML 조직에서 신입 ML Engineer 인력 요청이 도착했습니다.</p><Facts items={[["필요 인력", `${p.demand_fte} FTE`], ["업무 준비 목표", p.target_date], ["기준일", p.baseline_date]]} /><p>FTE는 전일제 근무자 1명에 해당하는 업무량입니다. 16 FTE는 조직 전체의 필요 인력이며 신규 채용 수가 아닙니다.</p><details open={phase > 0}><summary>요청서와 목표 브리핑</summary><p>필요한 인력은 충분한가 → 어떤 기초가 필요한가 → 어떻게 확인할 것인가 → 목표일까지 실제 업무를 할 수 있는가.</p><p>현재 인원과 확정된 이동을 확인한 뒤 확보 규모를 계산합니다.</p></details></>;
 case 'M1-02': return <><Facts items={[["현재 인력", p.current_fte], ["확정 전입", `+${p.confirmed_transfer_in}`], ["확정 전출", `−${p.confirmed_transfer_out}`], ["확정 입사", p.confirmed_joiners]]} /><p>전입·전출은 조직 사이에서 이미 확정된 이동입니다.</p>{phase > 0 && <><h4>목표일 공급 계산</h4><p>{p.current_fte} + {p.confirmed_transfer_in} − {p.confirmed_transfer_out} + {p.confirmed_joiners} = {p.current_fte + p.confirmed_transfer_in - p.confirmed_transfer_out + p.confirmed_joiners} FTE</p><p>인력 차이: {p.demand_fte} − {p.forecast_supply_fte} = {p.workforce_gap} FTE</p><p>초기 전망 {p.forecast_supply_fte / p.demand_fte * 100}%는 최종 실제 결과가 아닙니다.</p></>}{phase > 1 && <><h4>확보 방식의 근거와 대안</h4><p>즉시 독립 수행이 필요하지 않고, 숙련 인력의 육성 여력과 6개월 업무 적응 기간이 있어 신입 외부채용을 계획했습니다.</p><details><summary>다른 대안과 재검토 조건</summary><p>경력채용: 즉시 전력이 핵심 조건이 아니므로 이번 기본안에서는 제외했습니다. 내부이동: 확정 이동을 반영해도 인력 차이가 남습니다. 육성·외부 자원도 검토하되, 조직 내 추가 인력 확보라는 요청을 기준으로 판단합니다.</p><p>목표일이 앞당겨지거나 멘토 여력이 줄면 다시 검토합니다.</p></details></>}</>;
 case 'M1-03': return <><p>실제 문제를 구조화하고, 기초를 바탕으로 구현·검증하며 동료와 해결책을 발전시키는 업무입니다.</p>{data.skills.map(s => <details key={s.skill_id}><summary>{label(s.requirement_type)} · {s.skill_name}</summary><p>{s.expected_evidence}</p><p className="m1-note">{s.classification_rationale}</p></details>)}</>;
 case 'M1-04': return <><span className="po-evidence">시나리오 공고 초안 · 직무 해석</span><h3>신입 ML Engineer</h3><p>현실의 문제를 구조화하고 작은 알고리즘을 구현·검증합니다. 새 기술을 학습하고 동료와 결과·한계를 공유합니다.</p><h4>입사 전 확인할 기초</h4><ul>{data.skills.filter(s => s.requirement_type === 'MUST').map(s => <li key={s.skill_id}>{s.skill_name}</li>)}</ul><p>운영 경험은 입사 후 업무와 멘토 지원으로 학습합니다.</p><p className="m1-note">기아 공식 공고 전문은 확보되지 않았습니다. 위 내용은 승인 인재 요건을 풀어 쓴 시나리오 초안입니다.</p></>;
 case 'M1-05': return <><p>검토 관점: 모호한 표현, 내부용어, 긴 문장, 필수·우대 요건의 혼재.</p><details><summary>문장과 인재 요건 연결</summary><p>“작은 알고리즘을 구현·검증합니다” → 알고리즘 구현 및 검증.</p><p>“운영 경험은 입사 후 학습합니다” → 필수요건으로 혼동하지 않도록 학습 영역을 분리합니다.</p></details><p>문구 확정은 채용담당자가 담당합니다. 자동 점수·외부 도구 연동은 없습니다.</p><p className="m1-note">별도 문구 승인 이력은 제공되지 않습니다. 검토 완료 건수를 만들지 않습니다.</p></>;
 case 'M1-06': return <><h3>지원 안내</h3><p>신입 ML Engineer · PeopleOps Office 합성 채용 시나리오</p><p>서류 → 사전검증 → 1차면접 → 2차면접 → 최종 검토 → 채용 제안</p><details><summary>무엇을 준비하나요?</summary><p>본인이 수행한 작업, 문제와 제약, 확인 방법, 수정한 결과를 구체적으로 설명할 수 있는 경험을 준비합니다.</p></details><p>지원 문항은 경험 탐색의 출발점입니다. 문장만으로 역량을 확정하지 않습니다.</p><p className="m1-note">실제 기업의 지원 페이지나 합격 가능성 안내가 아닙니다.</p></>;
 case 'M1-07': return <><h4>대상 → 메시지 → 콘텐츠 → 채널</h4><p>대상: ML 기초와 구현 경험을 가진 신입 인재.</p><p>메시지: 현실의 문제를 다루고 동료와 검증하며 성장하는 업무.</p><p>콘텐츠: 실제 문제 예시, 업무 방식, 검증 과정, 학습 지원.</p><p>채널: 직무 관심 커뮤니티·대학 채널·채용 플랫폼에서 대상과 메시지가 만나는 접점을 검토합니다.</p><p className="m1-note">채널은 유입 경로이며 후보 품질의 대리변수가 아닙니다. 효과 분석은 여기서 수행하지 않습니다.</p></>;
 case 'M1-08': return <><p>제공된 지원 문항의 주제와 후속 확인점을 봅니다.</p>{['성장 경험 → 새 기술을 어떤 방법으로 익히고 확인했는가?', '중요 역량과 노력 → 본인이 수행한 구현과 검증 기록이 있는가?', '가치와 행동 → 어떤 상황에서 누구와 무엇을 하고 피드백을 반영했는가?'].map(text => <details key={text}><summary>{text.split(' → ')[0]}</summary><p>{text.split(' → ')[1]}</p><p>자기기술을 직접 확인할 질문으로 연결하며 역량을 확정하지 않습니다.</p></details>)}<p className="m1-note">제공 캡처의 문항 취지를 요약했습니다. 공식 원문 URL·게시일과 공고 전문은 확인 대기입니다.</p></>;
 case 'M1-09': return <><Funnel /><Capacity phase={0} /><p>면접 60분 × 평가자 3명 = 후보당 3 person-hours. 평가 조정은 별도 활동입니다.</p></>;
 case 'M1-10': return <><p>명시적인 공개 기본요건 위반과 후속 검증할 경험을 구분합니다. 미관찰을 역량 부족으로 바꾸지 않습니다.</p><Facts items={[["제출", data.funnel[1].actual], ["서류 통과", data.funnel[2].actual]]} /><p className="m1-note">검증된 공개 기본요건이 없어 임의의 서류 탈락 기준을 만들지 않았습니다.</p></>;
 case 'M1-11': return <><p>역량검사는 활동 이벤트만, 코딩테스트는 구현·검증 기초의 직접 근거를 기록합니다. 실제 기업 문항은 재현하지 않습니다.</p><Facts items={[["사전검증 통과", data.funnel[3].actual]]} /><p>전형 진행 판단과 최종 채용 판단은 서로 다릅니다.</p></>;
 case 'M1-12': return <Capacity phase={phase} />;
 case 'M1-13': return <><h4>한 번의 면접, 세 평가영역</h4><p>지원자 1명 + 평가자 3명 · 단일 60분 Session</p><ul><li>기술평가: 문제 구조화·ML/수리 기초</li><li>AI 문제해결 과제: 문제 구조화·구현 및 검증</li><li>실무진 질의: 학습·협업·관련 경험</li></ul><p>영역 시간을 세 번 합산하지 않습니다. 개인 역할과 실제 수행·검증을 관찰합니다.</p><p className="m1-note">직무 해석에 기반한 합성 설계이며 기아 공식 운영정책이 아닙니다.</p></>;
 case 'M1-14': return <><p>아래 판단 질문을 열어 원자료와 평가자의 관찰을 확인하세요.</p><p>기술 핵심 역량 각각의 직접 근거를 구분합니다. 자기기술은 직접 검증을 대신하지 않습니다.</p></>;
 case 'M1-15': return <><p>근거가 판단 가능하다는 것과 충분한 역량이라는 것은 다릅니다. 직접 관찰한 제한적 근거도 판단 가능성에 포함됩니다.</p><Facts items={[["1차 진입", data.interview.entered], ["다음 단계 진행", data.interview.advanced], ["직접 근거 비진행", data.interview.failed], ["대기 / 확인 중", data.interview.waiting], ["철회", data.interview.withdrawn]]} /><p>평가 조정은 해석 차이나 의미 있는 충돌이 있을 때만 수행합니다. 평균 점수로 차이를 지우지 않습니다.</p></>;
 case 'M1-16': return <><p>지원자 1명, 평가자 2명, 약 30분의 합성 면접입니다.</p><p>학습·협업·가치와 행동을 구체적 과거 상황에서 확인합니다. 기술평가를 반복하거나 문화 적합도 점수를 만들지 않습니다.</p></>;
 case 'M1-17': return <><p>필수 역량의 판단 가능성, 남은 불확실성, 입사 후 학습할 영역을 함께 검토합니다.</p><p>아래 사례에서 보류 이유와 추가 확인 계획을 확인하세요. 보류는 최종 종료 상태가 아닙니다.</p></>;
 case 'M1-18': return <><p>보류 시 정의한 질문에만 대응하는 근거를 한 차례 추가 확인합니다. 전체 면접의 반복이나 통과를 위한 구제 절차가 아닙니다.</p></>;
 case 'M1-19': return <><p>새 관찰을 포함한 역량별 판단과 최종 재검토를 연결합니다. 필수 역량 자체를 판단할 수 없다면 채용 제안을 진행하지 않습니다.</p><p>한 차례 추가 확인 후에는 진행 또는 진행 종료로 기록하며 보류를 반복하지 않습니다.</p></>;
 case 'M1-20': return <><Facts items={[["채용 제안", o.offered], ["수락", o.accepted], ["거절", o.declined], ["기한 만료", o.expired]]} /><p>수락·거절은 관측된 응답입니다. 기한 만료는 응답 없이 기한이 지난 상태이며 사유는 확인되지 않았습니다.</p><p>수락 ≠ 입사. 선발 판단과 이후 응답 이력은 구분합니다.</p></>;
 case 'M1-21': return <><Facts items={[["수락", o.accepted], ["입사 전 철회", o.preJoinWithdrawal], ["입사", o.joined]]} /><h3>입사 ≠ 업무 준비 완료</h3><p>입사는 인력 이벤트입니다. 실제 업무 수행 근거와 사람의 확인은 이후에 별도로 기록합니다.</p></>;
 case 'M1-22': return <><p>채용 판단의 업무 관련 근거와 개인별 학습 과제를 연결합니다.</p><Facts items={[["입사자", o.joined], ["개인별 확인·학습 항목", o.gaps], ["업무 적응 과제", o.tasks]]} /><p>개인별 요구 → 1·3·6개월 과제 → 업무 산출물 → 멘토 확인으로 이어집니다.</p><p>Values 답변과 선발 논의 전체를 멘토에게 넘기지 않습니다. 6개월은 계획이며 자동 업무 준비 조건이 아닙니다.</p></>;
 case 'M1-23': return <><h3>JOINED ≠ READY</h3><Facts items={[["입사", o.joined], ["업무 준비 확인", o.ready], ["목표일까지 준비 확인", o.targetDateReady]]} /><p>입사 후 업무 근거 + 사람의 확인이 있어야 업무 준비 완료로 기록합니다. 날짜 경과나 체크리스트 완료만으로 판정하지 않습니다.</p><details><summary>입사 후 업무 근거와 사람의 확인 기록</summary>{data.readyProof.map(record => <details key={record.id}><summary>업무 준비 확인 · {record.effectiveAt.slice(0, 10)}</summary><p>온보딩 멘토 확인: {record.confirmedAt.slice(0, 10)}</p><p>{record.reason}</p>{record.tasks.map(task => <p key={task.id}>{task.observedAt.slice(0, 10)} · {task.action}<code className="m1-record-id">{task.sourceRef}</code></p>)}<code className="m1-record-id">{record.id} · {record.confirmedBy}</code></details>)}</details><p className="m1-note">목표일 {p.target_date} / 관측 종료 {data.observationEnd.slice(0, 10)}. 두 기준일을 구분합니다.</p></>;
 case 'M1-24': return <><h3>채용 과정 · 계획과 실제</h3><Funnel actual /><h3>인력과 업무 준비</h3><Facts items={[["입사 목표", p.target_join], ["실제 입사", o.joined], ["업무 준비 확인", o.ready], ["목표일까지 준비 확인", o.targetDateReady]]} /><h3>운영시간 · 실제</h3><Facts items={[["면접 소비", `${c.consumed}h`], ["예약 해제", `${c.released}h`], ["별도 평가 조정", `${c.calibrationCount}건 / ${c.calibrationHours}h`]]} /><p>계획과 실제에 차이가 있습니다. 원인과 개선안은 다음 Mission의 분석에서 검토합니다.</p></>;
 case 'M1-25': return <><h3>인력 요청에서 업무 준비까지</h3><p>인력계획 → 인재 정의 → 채용 설계 → 지원자 검증 → 인재 확보 → 업무 준비</p><p>사람이 어떤 근거로 판단했는지, 실제로 어떤 사건이 발생했는지 확인했습니다.</p><p>다음 Mission은 이 v1 데이터를 바탕으로 새로운 인력 요청과 분석 질문을 검토합니다. 아직 분석을 시작하지 않습니다.</p></>;
 default: return null;
 }
}
